language: swift
osx_image: xcode12.5
script:
  - set -o pipefail
  - xcodebuild -project Sdifft.xcodeproj -scheme Sdifft-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' -configuration Release ONLY_ACTIVE_ARCH=YES  -enableCodeCoverage YES test | xcpretty
  - bash <(curl -s https://codecov.io/bash) -cF ios -X fix --verbose
